"""Generates the listing artwork vector drawables.

Each listing image is a soft tinted panel with a subject glyph drawn on top, so
thumbnails are visually distinct without shipping binary photo assets. Re-run
after editing SUBJECTS to regenerate.
"""
import pathlib

OUT = pathlib.Path(__file__).resolve().parents[1] / "app/src/main/res/drawable"

TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/gen_listing_drawables.py - do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="160dp"
    android:height="120dp"
    android:viewportWidth="160"
    android:viewportHeight="120">
    <path
        android:fillColor="{bg}"
        android:pathData="M0,0h160v120h-160z" />
{glyph}
</vector>
"""

GLYPH = '    <path\n        android:fillColor="{c}"\n        android:pathData="{d}" />'
STROKE = ('    <path\n        android:strokeColor="{c}"\n        android:strokeWidth="{w}"\n'
          '        android:strokeLineCap="round"\n        android:strokeLineJoin="round"\n'
          '        android:fillColor="#00000000"\n        android:pathData="{d}" />')


def fill(d, c):
    return GLYPH.format(d=d, c=c)


def stroke(d, c, w=4):
    return STROKE.format(d=d, c=c, w=w)


# Palette-consistent backdrops: green-tinted for services, amber-tinted for goods.
SERVICE_BG = "#E4EFEA"
GOODS_BG = "#F2E9DC"
SERVICE_INK = "#1F7A5C"
GOODS_INK = "#9A6320"


def subjects():
    s, g = SERVICE_INK, GOODS_INK
    return {
        # --- Services -------------------------------------------------------
        # Lightning bolt + plug prongs
        "listing_electrical": (SERVICE_BG, [
            fill("M86,26L60,64h18l-6,32l28,-40h-18z", s),
            stroke("M44,90h72", s, 3),
        ]),
        # Open book with pencil
        "listing_tuition": (SERVICE_BG, [
            stroke("M46,40c10,-6 24,-6 34,2c10,-8 24,-8 34,-2v42c-10,-6 -24,-6 -34,2"
                   "c-10,-8 -24,-8 -34,-2z", s),
            stroke("M80,42v44", s, 3),
        ]),
        # Spray bottle
        "listing_cleaning": (SERVICE_BG, [
            stroke("M68,44h20v46a8,8 0 0,1 -8,8h-4a8,8 0 0,1 -8,-8z", s),
            stroke("M72,44v-8h12v8", s, 3),
            stroke("M88,50h14M88,58h10", s, 3),
        ]),
        # Potted plant
        "listing_garden": (SERVICE_BG, [
            stroke("M80,86v-26", s, 3),
            stroke("M80,64c-12,0 -20,-8 -20,-18c12,0 20,8 20,18z", s, 3),
            stroke("M80,64c12,0 20,-8 20,-18c-12,0 -20,8 -20,18z", s, 3),
            stroke("M62,86h36l-4,14h-28z", s),
        ]),
        # Shopping basket
        "listing_errands": (SERVICE_BG, [
            stroke("M52,54h56l-6,38h-44z", s),
            stroke("M68,54l6,-14M92,54l-6,-14", s, 3),
            stroke("M70,66v14M90,66v14", s, 3),
        ]),
        # Dog / paw print
        "listing_petcare": (SERVICE_BG, [
            fill("M80,64m-14,0a14,12 0,1 1,28 0a14,12 0,1 1,-28 0", s),
            fill("M60,46m-7,0a7,8 0,1 1,14 0a7,8 0,1 1,-14 0", s),
            fill("M100,46m-7,0a7,8 0,1 1,14 0a7,8 0,1 1,-14 0", s),
            fill("M46,66m-6,0a6,7 0,1 1,12 0a6,7 0,1 1,-12 0", s),
            fill("M114,66m-6,0a6,7 0,1 1,12 0a6,7 0,1 1,-12 0", s),
        ]),
        # --- Marketplace ----------------------------------------------------
        # Desk with drawer
        "listing_desk": (GOODS_BG, [
            stroke("M40,52h80v12h-80z", g),
            stroke("M46,64v32M114,64v32", g, 3),
            stroke("M78,68h36v20h-36z", g, 3),
            stroke("M90,78h12", g, 3),
        ]),
        # Bicycle
        "listing_bicycle": (GOODS_BG, [
            stroke("M54,82m-16,0a16,16 0,1 1,32 0a16,16 0,1 1,-32 0", g, 3),
            stroke("M110,82m-16,0a16,16 0,1 1,32 0a16,16 0,1 1,-32 0", g, 3),
            stroke("M54,82l20,-30h18l16,30M74,52h-14", g, 3),
            stroke("M82,82h-28", g, 3),
        ]),
        # Mini fridge
        "listing_fridge": (GOODS_BG, [
            stroke("M56,26h48v72h-48z", g),
            stroke("M56,54h48", g, 3),
            stroke("M64,38v10M64,64v12", g, 3),
        ]),
        # Sofa
        "listing_sofa": (GOODS_BG, [
            stroke("M40,60a8,8 0,0 1,16 0v18h48v-18a8,8 0,0 1,16 0v26h-80z", g),
            stroke("M56,78h48", g, 3),
            stroke("M52,86v8M108,86v8", g, 3),
        ]),
        # Stack of books
        "listing_books": (GOODS_BG, [
            stroke("M44,44h58v14h-58z", g, 3),
            stroke("M50,58h58v14h-58z", g, 3),
            stroke("M44,72h58v14h-58z", g, 3),
        ]),
        # Blender
        "listing_blender": (GOODS_BG, [
            stroke("M62,28h36l-6,42h-24z", g),
            stroke("M66,70h28v10h-28z", g, 3),
            stroke("M62,80h36v16h-36z", g),
        ]),
    }


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for name, (bg, glyphs) in subjects().items():
        svg = TEMPLATE.format(bg=bg, glyph="\n".join(glyphs))
        (OUT / f"{name}.xml").write_text(svg, encoding="utf-8")
        print("wrote", name)


if __name__ == "__main__":
    main()
